Do not suggest using Lazy.t instead of lazy_t
The distinction does not seem to actually matter so people don't have to feel bad about using `lazy_t`. `ocamlc` even shows inferred types as `lazy_t` against the advice of the documentation, making it hard to deprecate `lazy_t` in user code:

```
module Deprecate = struct
  type _ lazy_t = | [@@deprecated "don't."]
end
open Deprecate
module S : sig
  val x : unit lazy_t (* should use Lazy.t instead *)
end = struct
  let x = lazy ()
end

(* compiler says:
Error: Signature mismatch:
       Modules do not match:
         sig val x : unit lazy_t end
       is not included in
         sig val x : unit Deprecate.lazy_t end
       Values do not match:
         val x : unit lazy_t
       is not included in
         val x : unit Deprecate.lazy_t
*)
```